# Since we really don't want any of Travis' Python
language: generic
sudo: false

python:
env:
  global:
    - MINICONDA_DIR="$HOME/miniconda"
    - GH_PAGES_DIR="$TRAVIS_BUILD_DIR/website/"
  matrix:
    - Python=3.4
    - Python=3.5
    - Task=website

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $MINICONDA_DIR
  - export PATH="$MINICONDA_DIR/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install nbconvert
  - if [[ $Task != 'website' ]]; then
      sed -i -e "s/python=3/python=$Python/" environment.yml;
    fi;

install:
  - if [[ $Task != 'website' ]]; then
      conda env create -q -f environment.yml;
      source activate gallery;
      $MINICONDA_DIR/envs/gallery/bin/python -m ipykernel install --user --name gallery;
      conda list -n gallery;
    fi

script:
  - if [[ $Task == 'website' ]]; then
      python nbconverter.py;
    else
      find notebooks/ -name \*.ipynb -print0 | xargs -0 -n1 jupyter nbconvert --execute --ExecutePreprocessor.timeout=180 --ExecutePreprocessor.kernel_name=gallery --to=notebook --stdout >| /dev/null;
    fi

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
    condition: $Task == 'website'
