 name: gallery
 channels:
   - conda-forge
 dependencies:
   - python=3
   - numpy=1.11
   - matplotlib
   - cartopy
   - jupyter
   - metpy
   - siphon
   - sphinx
   - sphinx-gallery
   - sphinx_rtd_theme
   - xarray
   - arm_pyart
